---
title: "Developing Data Products Project"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Introduction

This peer assessed assignment has two parts. First,  a Shiny application is created and deployed it on Rstudio's servers. Second, Rstudio Presenter is used to prepare a reproducible pitch presentation about the application.

- The World Bank collects a lot of data for tracking the development of nations: income, investment, poverty, 
social/gender equality, education... It can be browsed and downloaded   <a href="https://data.worldbank.org/" target="_blank">here</a>.


- In this project the relation between GDP (Gross Domestic Product)per person and life expectancy at birth is depicted, taken the data from 2015 (last year available). There's a positive relation: with higher GDP per person, higher life expectancy is expected.

- Data has been downloaded from the above URL and stored in the file World_Bank_indicators.csv .

## Shiny Application
<a href="https://cplesp.shinyapps.io/worldbank" target="_blank">here</a>

* ui.R
* server.R


## Presentation
<a href="http://rpubs.com/cplesp/lifeexp" target="_blank">follow this link</a>

* worldBankIndicators.Rpres
* worldBankIndicators.md
* worldBankIndicators-rpubs.html




